# Generated by Django 4.2.5 on 2024-02-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='sdp',
        ),
    ]
