# Generated by Django 4.2.5 on 2024-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0002_alter_article_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
