# Generated by Django 4.1.13 on 2024-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0003_alter_article_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caruserinfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
