# Generated by Django 4.1.13 on 2024-03-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0004_caruserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruserinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='caruserinfo',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='caruserinfo',
            table='userbooked',
        ),
    ]
