# Generated by Django 4.1.13 on 2024-04-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0005_caruserinfo_name_caruserinfo_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caruserinfo',
        ),
    ]
