# Generated by Django 4.1.13 on 2024-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0006_delete_caruserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caruserinfo',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'userbooked',
            },
        ),
    ]
