# Generated by Django 5.0.4 on 2024-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0008_alter_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caruserinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='caruserinfo',
            name='t',
            field=models.IntegerField(default=0),
        ),
    ]
