# Generated by Django 5.0.4 on 2024-04-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0009_remove_caruserinfo_password_caruserinfo_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'userfeed',
            },
        ),
    ]
